# Generated by Django 3.2.7 on 2021-09-19 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20210919_1426'),
        ('preferences', '0001_initial'),
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='file/attachment/')),
                ('attachment1', models.TextField(blank=True, null=True)),
                ('attach_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='adviser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paper_adviser', to='account.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='co_adviser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paper_co_adviser', to='account.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paper_course', to='preferences.unit2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='mode',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='semsy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paper_semsy', to='preferences.semsy'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaperComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_comment_created', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_comment_papers', to='paper.paper')),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachement_comment_attachments', to='paper.attachment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_comment_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_papers', to='paper.paper'),
        ),
    ]
