# Generated by Django 3.2.7 on 2021-09-19 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0002_auto_20210919_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_adviser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paper',
            name='co_adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_co_adviser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paper',
            name='proponent1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_proponent1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paper',
            name='proponent2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_proponent2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paper',
            name='proponent3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_proponent3', to=settings.AUTH_USER_MODEL),
        ),
    ]
