# Generated by Django 3.2.7 on 2021-09-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_auto_20210919_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='research_level',
            field=models.CharField(choices=[('UNDERGRADUATE', 'UNDERGRADUATE'), ('MASTERS', 'MASTERS'), ('DOCTOR', 'DOCTOR')], default='UNDERGRADUATE', max_length=50),
        ),
        migrations.AddField(
            model_name='paper',
            name='research_type',
            field=models.CharField(choices=[('CAPSTONE', 'CAPSTONE'), ('THESIS', 'THESIS')], default='THESIS', max_length=50),
        ),
    ]
