# Generated by Django 3.2.7 on 2021-09-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_auto_20210923_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
