# Generated by Django 3.2.7 on 2021-09-23 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20210923_2348'),
        ('paper', '0005_paper_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='research_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_research_level', to='preferences.reserchlevel'),
        ),
    ]
