# Generated by Django 3.2.7 on 2021-09-24 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20210923_2348'),
        ('paper', '0007_auto_20210923_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_course', to='preferences.unit2'),
        ),
    ]
