# Generated by Django 3.2.7 on 2021-09-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210919_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('FACULTY', 'FACULTY'), ('STUDENT', 'STUDENT'), ('ADMIN', 'ADMIN'), ('STAFF', 'STAFF')], max_length=50, null=True),
        ),
    ]
