# Generated by Django 3.2.7 on 2021-09-19 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('ext_name', models.CharField(blank=True, max_length=10, null=True)),
                ('account_type', models.CharField(max_length=50)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/account/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_unit2', to='preferences.unit2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
