# Generated by Django 3.2.7 on 2021-09-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sec',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='yr',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
