# Generated by Django 3.2.7 on 2021-09-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210919_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ext_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='picture',
        ),
    ]
